apiVersion: v1
kind: Service
metadata:
  name: balance-new-service
spec:
  type: ClusterIP
  selector:
    app: balance-new
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
