apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-gateway
  template:
    metadata:
      labels:
        app: balance-gateway
    spec:
      containers:
      - name: balance-gateway
        image: yourrepo/balance-gateway:latest
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"