apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balance-new-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/use-gzip: "true"
    nginx.ingress.kubernetes.io/gzip-types: "*"
spec:
  rules:
  - host: lscloud.dev.totvs.app
    http:
      paths:
      - path: /api/balance/old
        pathType: Prefix
        backend:
          service:
            name: balance-gateway
            port:
              number: 80      