apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-new-second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-new-second
  template:
    metadata:
      labels:
        app: balance-new-second
    spec:
      containers:
      - name: balance-new-second
        image: ghcr.io/salatielbairros/newsecondapp:latest
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__Redis
          value: "telemetry-redis-standalone-svc-dev:6379,password=123456"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"        
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http        
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"