apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balance-old
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/balance/new/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/use-gzip: "true"
    nginx.ingress.kubernetes.io/gzip-types: "*"
spec:
  rules:
  - host: lscloud.dev.totvs.app
    http:
      paths:
      - path: /api/balance/old/(.*)        
        pathType: ImplementationSpecific
        backend:
          service:
            name: balance-new-service
            port:
              number: 80
